{% set name = "blessings" %}
{% set version = "1.6.1" %}
{% set sha256 = "74919575885552e14bc24a68f8b539690bd1b5629180faa830b1a25b8c7fb6ea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - blessings

about:
  home: https://github.com/erikrose/blessings
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A thin, practical wrapper around terminal capabilities in Python'
  dev_url: https://github.com/erikrose/blessings

extra:
  recipe-maintainers:
    - synapticarbors
