travis:
  secure:
    BINSTAR_TOKEN: dHQrmg8+ic9Aa5Jx36xSv/WgXXepkyHnpPuXkqICRQ+dV7hUyMtG0p/jaCUEA5zZOudT3Q70Sy5FT/+dh5GLBBeF0Kgf4USqZq7NFwAFPM25qPtVw9TBxpFPicpshWR3T2Uo771fY4DqSzSoFCb0joVdOXdh724l7P30Mhb8Q31MK4Rzix2Vj1YHltcvAwgOdyjaqbU907w5+Jcy3o8LR/FVTK+u5IFISuScXDKn9Sj1QeLfUJbgcMCZLQ4kdDu7cVqCQOW2jk+MDtY624e6EL1dGHVdDs3vZozluwtR8FDs9PDd46OzbBTvka1Om/fPaRpbnfPDFDhSTg4bdl2J5mtNvCBTMR1YRPXTFeoMfl/j7+VKFHIuzE4c+ewjT8M4IyG5wx+QDYjZBO4Q75RhOA1eeD4xZafmun2nD6BMdf9iqBtXq3qu8rIA17LHcnx8IaFV6BFv6Fp21+vZ5Ft3lZy1/SCzUlGdVrzWx0dAcIeqwb5lRuSMZsOrL4psag9/499mvg3x3VXBGvqaft2xq0yyfKEz37QaU6tM8rPcJMHlRWHG8RJodO05SE4UiGwx5i8FB4iVct/0Q52zGDW6rMgunOdcwAKFjn1jhUkmObsxkOlSAqbdYjYMDWgmm/7I/2AYu8uu0VJJ+Oa8Ba5xp96SmS4a0rULMajohyPJiRA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
