travis:
  secure:
    BINSTAR_TOKEN: JEynEf50mV/BnFogpKPYUsLiZXG6VQZNM9NHg251Hkeujc6FfDAct2pnbaKQW1SRMo4hSPNfaUeA+AmJpiHw3fSDi1goVmHGubmJKxmHCoVCk4xURSjycefJ0GVBMPF8h9Ts9cECccgo229Xzqflr3qauGsGn0gNpjjWONOPNWeeR7Kpt0Uj1Tx/laid1Ow6OSp0Puw/uDNTaEQ7QwtUZHqfcNuw5b6b+2/NVhXyQBYAJ+d5wcrVRelPihecPfQqIRgFAb8P8UVkT8HC5gH8QeMiaGokQh4FPCwKZK9vKdAER3n1s9zxtVaNrfCQ2W7rtJK7PCtX+ElmCTWV6wRKcomgbZc5+2hO6025CyIlOtWPqN5Xlp9qpqU0mYdFbxt1oxWU04xYLg38S6ddcLola8T2ldbDtF/Rn6lp97ZpzfPw/Wv1iUANgCPksrgp8bZP8MocTsFWmqeJUZzIpKp2gBmCdRKFty8SQIwycgL4muZ6/ghov5hIDLsoFPxWBb96cJuSCO46Odg1z1kUGlARqJ+QPxGQpzSUaV/MABYnrToROsXzF0P+d1c3h1wBuRDdou2V+lxAbl6voO8ujsLc5OI122WW69mZOnNU7ncZwxQjWdM7JdN2mMmaSHwQkJMlv+f4JZ/koIfsmTrLUXqTRoA9cMlFXPvoQeRF9L7BQUc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
